<?php
 /**
* Ti Order Comment Module
*
* @category    Ti
* @package     Ti_OrderComment
* @copyright   Copyright (c) 2014 Ti Technologies (http://www.titechnologies.in)
* @link        http://www.titechnologies.in
*/

?>
<style>
    .buttons-set {
        text-align: left;
    }
</style>
<form action="" id="checkout-agreements" onsubmit="return false;">
    <div class="buttons-set">
        <ul class="form-list">
            <li>
                <fieldset>
                    <ul>
                        <li class="wide">
                            <label for="ordercomment-comment"><?php echo $feedbackTitle = Mage::getStoreConfig('ordercomment/ordercomment_group/ordercomment_question'); ?></label>
                            <div class="input-box">
                                <?php
								$comments = Mage::getStoreConfig('ordercomment/ordercomment_group/ordercomment_comments');
								$oneByOne = explode(";", $comments);
								foreach($oneByOne as $comment) {
									if($comment){
									?>
									<li class="control">
										<input type="radio" id="ordercomment-comment" name="ordercomment[comment]" value="<?php echo trim($comment); ?>"><?php echo '&nbsp;'.trim($comment); ?>
									</li>
									<?php
									}
                                }
                                ?>
                                <li class="control"><?php echo $feedbackTitle = Mage::getStoreConfig('ordercomment/ordercomment_group/ordercomment_boxtitle'); ?></label>
                                </li>
                                <li class="control">
                                    <textarea name="custom_comment" id="custom_comment" rows="10" cols="60"></textarea>
                                </li>
                            </div>

                        </li>
                    </ul>
                </fieldset>
            </li>
        </ul>
    </div>

    <?php if ($this->getAgreements()): ?>
        <ol class="checkout-agreements">
            <?php foreach ($this->getAgreements() as $_a): ?>
            <li>
                <div class="agreement-content"<?php echo ($_a->getContentHeight() ? ' style="height:' . $_a->getContentHeight() . '"' : '')?>>
                    <?php if ($_a->getIsHtml()):?>
                    <?php echo $_a->getContent() ?>
                    <?php else:?>
                    <?php echo nl2br($this->htmlEscape($_a->getContent())) ?>
                    <?php endif; ?>
                </div>
                <p class="agree">
                    <input type="checkbox" id="agreement-<?php echo $_a->getId()?>" name="agreement[<?php echo $_a->getId()?>]" value="1" title="<?php echo $this->htmlEscape($_a->getCheckboxText()) ?>" class="checkbox" /><label for="agreement-<?php echo $_a->getId()?>"><?php echo $_a->getIsHtml() ? $_a->getCheckboxText() : $this->htmlEscape($_a->getCheckboxText()) ?></label>
                </p>
            </li>
            <?php endforeach ?>
        </ol>
    <?php endif; ?>
</form>
